### ISSUE TITLE
Truth values in ABAP

### ISSUE THREAD

**Issue by Suncatcher** [guettli/why-i-like-django-and-sap#2]
> "Therefore, the result of a logical expression cannot be assigned directly to a data object." ... this quote is from this page: https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-US/abendataobjects_true_value_guidl.htm
It this is not true, then the sap docs are not valid.

This is really an interesting question what they meant by this statement, that they cannot be directly assigned. It worth asking on SO what the community thinks about it.

The example I gave 

    DATA: bool TYPE abap_bool.

    bool = cl_ciap_rounding=>is_integer( 5 ).

is compiled in ABAP, `is_integer( )` method returns `abap_bool` and it can be assigned. Maybe because of SAP treats `abap_bool` not a real boolean type they writes this. Who knows.

**Comment by guettli** [comment]
>  It worth asking on SO what the community thinks about it.

You think you can find the answer in the heads of humans? For this question I would look the implementation or the docs.

**Comment by Suncatcher** [comment]
Actually in [ABAP Clean Code guidelines](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#use-xsdbool-to-set-boolean-variables) `xsdbool` function is mentioned as recommended way for setting boolean variables in ABAP.
As these sections are maintained by current SAP employees and proven community experts I suppose it is an error-proof way.
So this passage from ABAP documentation is misleading and they wanted to say smth else.

**Comment by guettli** [comment]
@Suncatcher if the ABAP documentation is misleading, wouldn't it make sense to update it? Do you know how to do this?

**Comment by Suncatcher** [comment]
To raise an [OSS ticket](https://blogs.sap.com/2016/05/11/create-a-oss-message-to-sap-support-team/)

**Comment by guettli** [comment]
@Suncatcher thank you

**Comment by guettli** [comment]
@Suncatcher  I updated the paragraph. Could you please have a look at it? https://github.com/guettli/why-i-like-django-and-sap/blob/master/README.md#djangopythonpostgres-support-for-booleans

**Comment by Suncatcher** [comment]
@guettli looks fine.

**Comment by guettli** [comment]
thank you!
